version: '3.9'

volumes:
  postgres_countries:
    driver: local

services:
  postgres-countries:
    image: postgres:latest
    container_name: postgres-countries
    volumes:
      - postgres_countries:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
