version: '3.9'

volumes:
  postgres_world:
    driver: local

services:
  postgres-world:
    image: postgres:latest
    container_name: postgres-world
    volumes:
      - postgres_world:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
